### ISSUE TITLE
Hang or runtime error in dialog on OS/X

### ISSUE THREAD

**Issue by vilcans** [balthild/native-dialog-rs#23]
When opening a dialog I have seen that process hang or give a runtime error. The easiest way to reproduce is with:

    cargo run --example tour

This stops right after I click the OK button on the second dialog (MessageConfirm: true):

    fatal runtime error: Rust cannot catch foreign exceptions
    Abort trap: 6

I did a git bisect and found that this problem started appearing in commit 896fa21835.

I also have seen my own app hang instead of giving an error when opening a dialog.

This happens on two different Macs. I can provide more information if needed.

**Comment by balthild** [comment]
What version of macOS are you using? I had just tested on an M1 MacMini (macOS 11) and didn't encounter this problem.

**Comment by vilcans** [comment]
I don't normally use a Mac but I dug up an old one that I have to check the version of, but the person originally reporting it runs Big Sur 11.6 on an Intel Mac.

**Comment by balthild** [comment]
Well, it's strange... I'll try testing on an Intel Mac later.

**Comment by balthild** [comment]
Hello, I've just published v0.5.6. Could you please try it and see if there's still a panic?

**Comment by vilcans** [comment]
Yes, I still get the same behavior as before in master when I run `cargo run --example tour`.

In case it helps, here's my app where I use native-dialog: https://github.com/vilcans/pixel_pen/ The behavior there is different. It does not panic, but instead freezes with the dialog still open, so you can't even click a button. It may or may not have the same cause as the panic.

**Comment by balthild** [comment]
It seems like the problem that apps freeze is caused by winit. See rust-windowing/winit#1779. I reproduced this problem with winit v0.24, and it's resolved in winit v0.26.

I've upgraded raw-window-handle to support winit v0.26 and published v0.6.0. Please confirm if there's still a freezing.

For the problem that foreign exceptions being thrown, I still have no idea...

**Comment by balthild** [comment]
Hello, I've just fixed some unsound code that violates the [memory management rules of Objective-C](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmRules.html). Maybe the foreign exceptions you've encountered are caused by them. Could you please test if there's still a panic in v0.6.1?

**Comment by vilcans** [comment]
I still get the foreign exception panic in the tour example in 0.6.1.

I haven't taken the time to upgrade winit as it's a transitive dependency in my app. I'll have to get back on that.

**Comment by vilcans** [comment]
I tested with the upgraded winit (0.26.1) which got rid of the beach ball hang and the upgraded native-dialog (0.6.3) which got rid of the panic.

So everything seems to work now.
